<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Article;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $articles = [
            [
                'title' => 'Panduan Lengkap Laravel 10 untuk Pemula',
                'slug' => 'panduan-lengkap-laravel-10-untuk-pemula',
                'excerpt' => 'Pelajari dasar-dasar Laravel 10 dari nol hingga mahir. Tutorial lengkap dengan contoh praktis untuk membangun aplikasi web modern.',
                'content' => 'Laravel adalah framework PHP yang paling populer saat ini. Dalam artikel ini, kita akan mempelajari dasar-dasar Laravel 10 mulai dari instalasi hingga deployment. Laravel menyediakan syntax yang elegan dan tools yang powerful untuk web development. Framework ini menggunakan pattern MVC (Model-View-Controller) yang memudahkan developer dalam mengorganisir kode. Dengan fitur-fitur seperti Eloquent ORM, Blade templating, dan Artisan CLI, Laravel menjadi pilihan utama untuk membangun aplikasi web yang scalable dan maintainable.',
                'category' => 'web-development',
                'author' => 'Ahmad Rizki',
                'author_title' => 'Senior Laravel Developer',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['laravel', 'php', 'web development', 'tutorial', 'framework'],
                'status' => 'published',
                'is_featured' => true,
                'views' => 1250,
                'published_at' => Carbon::now()->subDays(5),
            ],
            [
                'title' => 'Mengenal JavaScript ES6+ dan Fitur Terbaru',
                'slug' => 'mengenal-javascript-es6-dan-fitur-terbaru',
                'excerpt' => 'Eksplorasi fitur-fitur terbaru JavaScript ES6+ yang akan membuat kode Anda lebih efisien dan modern.',
                'content' => 'JavaScript ES6+ membawa banyak fitur baru yang revolusioner. Arrow functions, template literals, destructuring, dan async/await adalah beberapa fitur yang mengubah cara kita menulis JavaScript. Fitur-fitur ini tidak hanya membuat kode lebih ringkas, tetapi juga lebih readable dan maintainable. Dalam artikel ini, kita akan membahas setiap fitur dengan contoh praktis yang dapat langsung diterapkan dalam project Anda.',
                'category' => 'web-development',
                'author' => 'Sarah Putri',
                'author_title' => 'Frontend Developer',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['javascript', 'es6', 'frontend', 'programming'],
                'status' => 'published',
                'is_featured' => true,
                'views' => 890,
                'published_at' => Carbon::now()->subDays(3),
            ],
            [
                'title' => 'Strategi Digital Marketing untuk UMKM',
                'slug' => 'strategi-digital-marketing-untuk-umkm',
                'excerpt' => 'Pelajari strategi digital marketing yang efektif dan terjangkau untuk mengembangkan bisnis UMKM Anda.',
                'content' => 'Digital marketing adalah kunci sukses UMKM di era digital. Dengan budget terbatas, UMKM harus pintar memilih strategi yang cost-effective namun impactful. Media sosial, Google My Business, content marketing, dan email marketing adalah beberapa strategi yang dapat diterapkan tanpa mengeluarkan biaya besar. Yang terpenting adalah konsistensi dan pemahaman terhadap target audience.',
                'category' => 'digital-marketing',
                'author' => 'Budi Santoso',
                'author_title' => 'Digital Marketing Specialist',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['digital marketing', 'umkm', 'bisnis', 'social media'],
                'status' => 'published',
                'is_featured' => false,
                'views' => 567,
                'published_at' => Carbon::now()->subDays(7),
            ],
            [
                'title' => 'Tren Desain UI/UX 2024',
                'slug' => 'tren-desain-ui-ux-2024',
                'excerpt' => 'Discover the latest UI/UX design trends that will dominate 2024 and how to implement them in your projects.',
                'content' => 'Dunia desain UI/UX terus berkembang dengan tren-tren baru yang menarik. Tahun 2024 akan didominasi oleh minimalism 2.0, dark mode implementation, micro-interactions, dan accessibility-first design. Designer harus memahami tren ini untuk menciptakan user experience yang optimal dan sesuai dengan ekspektasi pengguna modern.',
                'category' => 'design',
                'author' => 'Maya Sari',
                'author_title' => 'UI/UX Designer',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['ui/ux', 'design', 'trends', '2024'],
                'status' => 'published',
                'is_featured' => true,
                'views' => 723,
                'published_at' => Carbon::now()->subDays(2),
            ],
            [
                'title' => 'Keamanan Cyber untuk Bisnis Kecil',
                'slug' => 'keamanan-cyber-untuk-bisnis-kecil',
                'excerpt' => 'Panduan praktis untuk melindungi bisnis kecil dari ancaman cyber security dengan budget terbatas.',
                'content' => 'Bisnis kecil sering menjadi target empuk cybercriminal karena sistem keamanan yang lemah. Namun, dengan strategi yang tepat dan tools yang affordable, bisnis kecil dapat melindungi diri dari ancaman cyber. Password management, two-factor authentication, regular backup, dan employee training adalah fondasi keamanan yang harus diterapkan.',
                'category' => 'technology',
                'author' => 'Andi Wijaya',
                'author_title' => 'Cybersecurity Consultant',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['cybersecurity', 'bisnis', 'keamanan', 'technology'],
                'status' => 'published',
                'is_featured' => false,
                'views' => 445,
                'published_at' => Carbon::now()->subDays(4),
            ],
            [
                'title' => 'Membangun Personal Branding di LinkedIn',
                'slug' => 'membangun-personal-branding-di-linkedin',
                'excerpt' => 'Tips dan strategi untuk membangun personal branding yang kuat di LinkedIn untuk meningkatkan karir profesional.',
                'content' => 'LinkedIn adalah platform terbaik untuk membangun personal branding profesional. Dengan strategi content yang tepat, optimasi profil yang baik, dan networking yang aktif, Anda dapat memposisikan diri sebagai thought leader di industri Anda. Konsistensi dalam sharing valuable content dan engaging dengan network adalah kunci sukses di LinkedIn.',
                'category' => 'career',
                'author' => 'Dina Rahayu',
                'author_title' => 'Career Coach',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['linkedin', 'personal branding', 'career', 'networking'],
                'status' => 'published',
                'is_featured' => false,
                'views' => 334,
                'published_at' => Carbon::now()->subDays(6),
            ],
            [
                'title' => 'React vs Vue.js: Perbandingan Framework Frontend 2024',
                'slug' => 'react-vs-vue-js-perbandingan-framework-frontend-2024',
                'excerpt' => 'Analisis mendalam perbandingan React dan Vue.js untuk membantu developer memilih framework yang tepat.',
                'content' => 'React dan Vue.js adalah dua framework frontend paling populer saat ini. Keduanya memiliki kelebihan dan kekurangan masing-masing. React lebih mature dengan ecosystem yang besar, sementara Vue.js lebih mudah dipelajari dengan learning curve yang gentle. Pilihan framework tergantung pada kebutuhan project, tim, dan long-term maintenance strategy.',
                'category' => 'web-development',
                'author' => 'Rizky Pratama',
                'author_title' => 'Frontend Architect',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['react', 'vue.js', 'frontend', 'comparison'],
                'status' => 'draft',
                'is_featured' => false,
                'views' => 0,
                'published_at' => null,
            ],
            [
                'title' => 'Optimasi SEO untuk E-commerce',
                'slug' => 'optimasi-seo-untuk-e-commerce',
                'excerpt' => 'Strategi SEO khusus untuk toko online agar produk Anda mudah ditemukan di search engine.',
                'content' => 'SEO untuk e-commerce memiliki tantangan unik dibandingkan website biasa. Product pages, category pages, dan technical SEO harus dioptimasi dengan baik. Keyword research untuk produk, optimasi product descriptions, dan structured data adalah beberapa aspek penting yang harus diperhatikan untuk meningkatkan visibility di search engine.',
                'category' => 'digital-marketing',
                'author' => 'Sinta Dewi',
                'author_title' => 'SEO Specialist',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['seo', 'e-commerce', 'digital marketing', 'optimization'],
                'status' => 'published',
                'is_featured' => false,
                'views' => 612,
                'published_at' => Carbon::now()->subDays(8),
            ],
            [
                'title' => 'Machine Learning untuk Pemula: Konsep Dasar',
                'slug' => 'machine-learning-untuk-pemula-konsep-dasar',
                'excerpt' => 'Pengenalan konsep dasar machine learning yang mudah dipahami untuk pemula yang ingin terjun ke AI.',
                'content' => 'Machine Learning adalah subset dari Artificial Intelligence yang memungkinkan komputer belajar tanpa diprogram secara eksplisit. Supervised learning, unsupervised learning, dan reinforcement learning adalah tiga kategori utama ML. Dengan tools seperti Python, scikit-learn, dan TensorFlow, siapa pun dapat mulai belajar machine learning.',
                'category' => 'technology',
                'author' => 'Dr. Fajar Nugroho',
                'author_title' => 'Data Scientist',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['machine learning', 'ai', 'data science', 'python'],
                'status' => 'draft',
                'is_featured' => false,
                'views' => 0,
                'published_at' => null,
            ],
            [
                'title' => 'Freelancing Tips: Cara Sukses Menjadi Freelancer',
                'slug' => 'freelancing-tips-cara-sukses-menjadi-freelancer',
                'excerpt' => 'Panduan lengkap untuk memulai dan sukses dalam karir freelancing dengan tips praktis dari freelancer berpengalaman.',
                'content' => 'Freelancing menawarkan kebebasan dan fleksibilitas, namun juga membutuhkan disiplin dan strategi yang tepat. Time management, client communication, pricing strategy, dan continuous learning adalah kunci sukses freelancer. Membangun portfolio yang kuat dan reputation yang baik adalah investasi jangka panjang untuk karir freelancing yang sustainable.',
                'category' => 'career',
                'author' => 'Indra Kusuma',
                'author_title' => 'Senior Freelancer',
                'author_avatar' => null,
                'featured_image' => null,
                'tags' => ['freelancing', 'career', 'tips', 'remote work'],
                'status' => 'published',
                'is_featured' => true,
                'views' => 987,
                'published_at' => Carbon::now()->subDays(1),
            ],
        ];

        foreach ($articles as $articleData) {
            Article::create($articleData);
        }
    }
}
