<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lokasi;

class LokasiSeeder extends Seeder
{
    public function run()
    {
        $lokasis = [
            [
                'nama' => 'PMI Provinsi DKI Jakarta',
                'alamat' => 'Jl. Kramat Raya No. 47, Jakarta Pusat',
                'kota' => 'Jakarta Pusat',
                'provinsi' => 'DKI Jakarta',
                'tanggal_operasional' => '2025-06-22',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '16:00:00',
                'kontak' => '021-3190223',
                'kapasitas' => 100,
                'gambar' => 'image/pmi/pmi1.png',
                'status' => 'aktif',
                'jenis' => 'provinsi',
                'latitude' => -6.1751,
                'longitude' => 106.8650,
                'deskripsi' => 'PMI Provinsi DKI Jakarta - Kantor Pusat'
            ],
            [
                'nama' => 'PMI Kota Jakarta Pusat',
                'alamat' => 'Jl. Pecenongan No. 82, Jakarta Pusat',
                'kota' => 'Jakarta Pusat',
                'provinsi' => 'DKI Jakarta',
                'tanggal_operasional' => '2025-06-25',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-3848432',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi2.png',
                'status' => 'aktif',
                'jenis' => 'kota',
                'latitude' => -6.1645,
                'longitude' => 106.8229,
                'deskripsi' => 'PMI Kota Jakarta Pusat'
            ],
            [
                'nama' => 'PMI Kota Jakarta Utara',
                'alamat' => 'Jl. Plumpang Semper No. 54, Jakarta Utara',
                'kota' => 'Jakarta Utara',
                'provinsi' => 'DKI Jakarta',
                'tanggal_operasional' => '2025-06-29',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-4001234',
                'kapasitas' => 80,
                'gambar' => 'image/pmi/pmi3.png',
                'status' => 'aktif',
                'jenis' => 'kota',
                'latitude' => -6.1088,
                'longitude' => 106.8826,
                'deskripsi' => 'PMI Kota Jakarta Utara'
            ],
            [
                'nama' => 'PMI Kota Jakarta Barat',
                'alamat' => 'Jl. Perdana No. 12, Jelambar, Jakarta Barat',
                'kota' => 'Jakarta Barat',
                'provinsi' => 'DKI Jakarta',
                'tanggal_operasional' => '2025-07-06',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-5601234',
                'kapasitas' => 70,
                'gambar' => 'image/pmi/pmi4.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -6.1652,
                'longitude' => 106.7537,
                'deskripsi' => 'PMI Kota Jakarta Barat'
            ],
            [
                'nama' => 'PMI Kota Jakarta Selatan',
                'alamat' => 'Jl. Raya Condet Pejaten, Pasar Minggu, Jakarta Selatan',
                'kota' => 'Jakarta Selatan',
                'provinsi' => 'DKI Jakarta',
                'tanggal_operasional' => '2025-07-13',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-7801234',
                'kapasitas' => 85,
                'gambar' => 'image/pmi/pmi5.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -6.2615,
                'longitude' => 106.8106,
                'deskripsi' => 'PMI Kota Jakarta Selatan'
            ],
            [
                'nama' => 'PMI Kota Jakarta Timur',
                'alamat' => 'Jl. I Gusti Ngurah Rai, Klender, Jakarta Timur',
                'kota' => 'Jakarta Timur',
                'provinsi' => 'DKI Jakarta',
                'tanggal_operasional' => '2025-07-13',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-7801234',
                'kapasitas' => 85,
                'gambar' => 'image/pmi/pmi6.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -6.2615,
                'longitude' => 106.8106,
                'deskripsi' => 'PMI Kota Jakarta Timur'
            ],
            [
                'nama' => 'PMI Kabupaten Kepulauan Seribu',
                'alamat' => 'Jl. Dermaga Pulau Pramuka, Kelurahan Pulau Panggang, Kepulauan Seribu Utara',
                'kota' => 'Kepulauan Seribu',
                'provinsi' => 'DKI Jakarta',
                'tanggal_operasional' => '2025-07-20',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-1234567',
                'kapasitas' => 90,
                'gambar' => 'image/pmi/pmi7.png',
                'status' => 'aktif',
                'jenis' => 'kota',
                'latitude' => -6.4023,
                'longitude' => 106.7942,
                'deskripsi' => 'PMI Kabupaten Kepulauan Seribu'
            ],
            [
                'nama' => 'PMI Kabupaten Bogor',
                'alamat' => 'Jl. KSR Dadi Kusmayadi, Kelurahan Tengah, Cibinong',
                'kota' => 'Bogor',
                'provinsi' => 'Jawa Barat',
                'tanggal_operasional' => '2025-07-27',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-7894561',
                'kapasitas' => 60,
                'gambar' => 'image/pmi/pmi8.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -6.2000,
                'longitude' => 106.8500,
                'deskripsi' => 'PMI Kabupaten Bogor'
            ],
            [
                'nama' => 'PMI Kabupaten Sukabumi',
                'alamat' => 'Jl. Cibolang KM. 07 No. 3, Cibolangkaler, Cisaat, Sukabumi',
                'kota' => 'Sukabumi',
                'provinsi' => 'Jawa Barat',
                'tanggal_operasional' => '2025-08-03',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-4567890',
                'kapasitas' => 70,
                'gambar' => 'image/pmi/pmi9.png',
                'status' => 'aktif',
                'jenis' => 'kota',
                'latitude' => -6.3911,
                'longitude' => 106.8283,
                'deskripsi' => 'PMI Kabupaten Sukabumi'
            ],
            [
                'nama' => 'PMI Kabupaten Cianjur',
                'alamat' => 'Jl. Dr. Muwardi No. 105, Cianjur',
                'kota' => 'Cianjur',
                'provinsi' => 'Jawa Barat',
                'tanggal_operasional' => '2025-08-10',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-3216549',
                'kapasitas' => 65,
                'gambar' => 'image/pmi/pmi10.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -6.2900,
                'longitude' => 106.6500,
                'deskripsi' => 'PMI Kabupaten Cianjur'
            ],
            [
                'nama' => 'PMI Kabupaten Bandung',
                'alamat' => 'Jl. Kopo Bihbul Km 16 Blk No. 14 (RSU Bihbul), Bandung',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'tanggal_operasional' => '2025-08-17',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-6543210',
                'kapasitas' => 80,
                'gambar' => 'image/pmi/pmi11.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.0000,
                'longitude' => 107.6000,
                'deskripsi' => 'PMI Kabupaten Bandung'
            ],
            [
                'nama' => 'PMI Kota Surabaya',
                'alamat' => 'Jl. Sumatera No. 71, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'tanggal_operasional' => '2025-08-17',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-6543210',
                'kapasitas' => 80,
                'gambar' => 'image/pmi/pmi12.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.0000,
                'longitude' => 107.6000,
                'deskripsi' => 'PMI Kota Surabaya'
            ],
            [
                'nama' => 'PMI Kabupaten Gresik',
                'alamat' => 'Jl. Dr. Wahidin Sudiro Husodo No. 93, Gresik',
                'kota' => 'Gresik',
                'provinsi' => 'Jawa Timur',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi13.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kabupaten Gresik'
            ],
            [
                'nama' => 'PMI Kabupaten Sidoarjo',
                'alamat' => 'Jl. A. Yani No. 12, Sidoarjo',
                'kota' => 'Sidoarjo',
                'provinsi' => 'Jawa Timur',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi14.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kabupaten Sidoarjo'
            ],
            [
                'nama' => 'PMI Kota Malang',
                'alamat' => 'Jl. Buring No. 10, Malang',
                'kota' => 'Malang',
                'provinsi' => 'Jawa Timur',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi15.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kota Malang'
            ],
            [
                'nama' => 'PMI Kota Medan',
                'alamat' => 'Jl. Palang Merah No. 17, Medan',
                'kota' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi16.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kota Medan'
            ],
            [
                'nama' => 'PMI Kabupaten Langkat',
                'alamat' => 'Jl. Imam Bonjol, Stabat',
                'kota' => 'Langkat',
                'provinsi' => 'Sumatera Utara',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi17.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kabupaten Langkat'
            ],
            [
                'nama' => 'PMI Kota Padang',
                'alamat' => 'Jl. Sawahan II No. 12, Padang',
                'kota' => 'Padang',
                'provinsi' => 'Sumatera Barat',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi18.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kota Padang'
            ],
            [
                'nama' => 'PMI Kota Bukittinggi',
                'alamat' => 'Jl. Dr. Rivai No. 17A, Bukittinggi',
                'kota' => 'Bukittinggi',
                'provinsi' => 'Sumatera Barat',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi19.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kota Bukittinggi'
            ],
            [
                'nama' => 'PMI Kota Denpasar',
                'alamat' => 'Jl. Imam Bonjol No. 182, Denpasar',
                'kota' => 'Denpasar',
                'provinsi' => 'Bali',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi20.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kota Denpasar'
            ],
            [
                'nama' => 'PMI Kota Mataram',
                'alamat' => 'Jl. Pejanggik No. 16, Mataram',
                'kota' => 'Mataram',
                'provinsi' => 'Nusa Tenggara Barat',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi21.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -7.9667,
                'longitude' => 112.6333,
                'deskripsi' => 'PMI Kota Mataram'
            ],
            [
                'nama' => 'PMI Kota Pontianak',
                'alamat' => 'Jl. Ahmad Yani, Pontianak',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi22.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -10.1962,
                'longitude' => 123.5862,
                'deskripsi' => 'PMI Kota Pontianak'
            ],
            [
                'nama' => 'PMI Kota Makassar',
                'alamat' => 'Jl. Lanto Daeng Pasewang No. 47, Makassar',
                'kota' => 'Makassar',
                'provinsi' => 'Sulawesi Selatan',
                'tanggal_operasional' => '2025-08-24',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'kontak' => '021-9876543',
                'kapasitas' => 75,
                'gambar' => 'image/pmi/pmi23.png',
                'status' => 'aktif',
                'jenis' => 'cabang',
                'latitude' => -1.2654,
                'longitude' => 116.8312,
                'deskripsi' => 'PMI Kota Makassar'
            ]
        ];

        foreach ($lokasis as $lokasi) {
            Lokasi::create($lokasi);
        }

        $this->command->info('Seeder lokasi berhasil dijalankan!');
    }
}
