<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Profile;
use Illuminate\Support\Facades\DB;

class ProfileSeeder extends Seeder
{
    public function run()
    {
        // Sample data for profiles
        $profiles = [
            [
                'user_id' => 1,
                'donor_code' => 'DNR001',
                'donor_id' => 'DONOR001',
                'ktp_number' => '1234567890123456',
                'name' => 'John Doe',
                'gender' => 'Laki-laki',
                'blood_type' => 'A',
                'rhesus' => 'POSITIF',
                'birth_date' => '1990-01-01',
                'birth_place' => 'Jakarta',
                'telephone' => '081234567890',
                'address' => 'Jl. Example No. 1',
                'province_id' => 1,
                'city_id' => 1,
                'district_id' => 1,
                'village_id' => 1,
                'postal_code' => '12345',
                'rt_rw' => '01/02',
                'occupation' => 'Software Engineer',
            ],
            [
                'user_id' => 2,
                'donor_code' => 'DNR002',
                'donor_id' => 'DONOR002',
                'ktp_number' => '6543210987654321',
                'name' => 'Jane Smith',
                'gender' => 'Perempuan',
                'blood_type' => 'B',
                'rhesus' => 'NEGATIF',
                'birth_date' => '1995-05-05',
                'birth_place' => 'Bandung',
                'telephone' => '082345678901',
                'address' => 'Jl. Sample No. 2',
                'province_id' => 2,
                'city_id' => 2,
                'district_id' => 2,
                'village_id' => 2,
                'postal_code' => '54321',
                'rt_rw' => '03/04',
                'occupation' => 'Data Scientist',
            ],
            [
                'user_id' => 3,
                'donor_code' => 'DNR003',
                'donor_id' => 'DONOR003',
                'ktp_number' => '7890123456789012',
                'name' => 'Alice Johnson',
                'gender' => 'Perempuan',
                'blood_type' => 'AB',
                'rhesus' => 'POSITIF',
                'birth_date' => '1988-02-15',
                'birth_place' => 'Surabaya',
                'telephone' => '083456789012',
                'address' => 'Jl. Sample No. 3',
                'province_id' => 3,
                'city_id' => 3,
                'district_id' => 3,
                'village_id' => 3,
                'postal_code' => '67890',
                'rt_rw' => '04/05',
                'occupation' => 'Product Manager',
            ],
            [
                'user_id' => 4,
                'donor_code' => 'DNR004',
                'donor_id' => 'DONOR004',
                'ktp_number' => '3456789012345678',
                'name' => 'Bob Brown',
                'gender' => 'Laki-laki',
                'blood_type' => 'O',
                'rhesus' => 'NEGATIF',
                'birth_date' => '1992-07-20',
                'birth_place' => 'Medan',
                'telephone' => '084567890123',
                'address' => 'Jl. Sample No. 4',
                'province_id' => 4,
                'city_id' => 4,
                'district_id' => 4,
                'village_id' => 4,
                'postal_code' => '13579',
                'rt_rw' => '06/07',
                'occupation' => 'Web Developer',
            ],
            [
                'user_id' => 5,
                'donor_code' => 'DNR005',
                'donor_id' => 'DONOR005',
                'ktp_number' => '4567890123456789',
                'name' => 'Charlie Green',
                'gender' => 'Laki-laki',
                'blood_type' => 'A',
                'rhesus' => 'POSITIF',
                'birth_date' => '1991-11-11',
                'birth_place' => 'Bali',
                'telephone' => '085678901234',
                'address' => 'Jl. Sample No. 5',
                'province_id' => 5,
                'city_id' => 5,
                'district_id' => 5,
                'village_id' => 5,
                'postal_code' => '24680',
                'rt_rw' => '08/09',
                'occupation' => 'Graphic Designer',
            ],
            [
                'user_id' => 6,
                'donor_code' => 'DNR006',
                'donor_id' => 'DONOR006',
                'ktp_number' => '5678901234567890',
                'name' => 'Diana Blue',
                'gender' => 'Perempuan',
                'blood_type' => 'B',
                'rhesus' => 'NEGATIF',
                'birth_date' => '1993-03-30',
                'birth_place' => 'Yogyakarta',
                'telephone' => '086789012345',
                'address' => 'Jl. Sample No. 6',
                'province_id' => 6,
                'city_id' => 6,
                'district_id' => 6,
                'village_id' => 6,
                'postal_code' => '13579',
                'rt_rw' => '10/11',
                'occupation' => 'Marketing Specialist',
            ],
            [
                'user_id' => 7,
                'donor_code' => 'DNR007',
                'donor_id' => 'DONOR007',
                'ktp_number' => '6789012345678901',
                'name' => 'Evelyn White',
                'gender' => 'Perempuan',
                'blood_type' => 'AB',
                'rhesus' => 'POSITIF',
                'birth_date' => '1985-04-25',
                'birth_place' => 'Semarang',
                'telephone' => '087890123456',
                'address' => 'Jl. Sample No. 7',
                'province_id' => 7,
                'city_id' => 7,
                'district_id' => 7,
                'village_id' => 7,
                'postal_code' => '98765',
                'rt_rw' => '12/13',
                'occupation' => 'HR Manager',
            ],
            [
                'user_id' => 8,
                'donor_code' => 'DNR008',
                'donor_id' => 'DONOR008',
                'ktp_number' => '7890123456789012',
                'name' => 'Frank Black',
                'gender' => 'Laki-laki',
                'blood_type' => 'O',
                'rhesus' => 'NEGATIF',
                'birth_date' => '1994-06-12',
                'birth_place' => 'Palembang',
                'telephone' => '088901234567',
                'address' => 'Jl. Sample No. 8',
                'province_id' => 8,
                'city_id' => 8,
                'district_id' => 8,
                'village_id' => 8,
                'postal_code' => '87654',
                'rt_rw' => '14/15',
                'occupation' => 'Sales Executive',
            ],
            [
                'user_id' => 9,
                'donor_code' => 'DNR009',
                'donor_id' => 'DONOR009',
                'ktp_number' => '8901234567890123',
                'name' => 'Grace Yellow',
                'gender' => 'Perempuan',
                'blood_type' => 'A',
                'rhesus' => 'POSITIF',
                'birth_date' => '1996-08-08',
                'birth_place' => 'Makassar',
                'telephone' => '089012345678',
                'address' => 'Jl. Sample No. 9',
                'province_id' => 9,
                'city_id' => 9,
                'district_id' => 9,
                'village_id' => 9,
                'postal_code' => '13579',
                'rt_rw' => '16/17',
                'occupation' => 'Content Writer',
            ],
            [
                'user_id' => 10,
                'donor_code' => 'DNR010',
                'donor_id' => 'DONOR010',
                'ktp_number' => '9012345678901234',
                'name' => 'Henry Gray',
                'gender' => 'Laki-laki',
                'blood_type' => 'B',
                'rhesus' => 'NEGATIF',
                'birth_date' => '1989-09-09',
                'birth_place' => 'Bandung',
                'telephone' => '090123456789',
                'address' => 'Jl. Sample No. 10',
                'province_id' => 10,
                'city_id' => 10,
                'district_id' => 10,
                'village_id' => 10,
                'postal_code' => '24680',
                'rt_rw' => '18/19',
                'occupation' => 'Business Analyst',
            ],
            [
                'user_id' => 11,
                'donor_code' => 'DNR011',
                'donor_id' => 'DONOR011',
                'ktp_number' => '0123456789012345',
                'name' => 'Isabella Red',
                'gender' => 'Perempuan',
                'blood_type' => 'AB',
                'rhesus' => 'POSITIF',
                'birth_date' => '1997-12-12',
                'birth_place' => 'Jakarta',
                'telephone' => '091234567890',
                'address' => 'Jl. Sample No. 11',
                'province_id' => 11,
                'city_id' => 11,
                'district_id' => 11,
                'village_id' => 11,
                'postal_code' => '12345',
                'rt_rw' => '20/21',
                'occupation' => 'Social Media Manager',
            ],
            [
                'user_id' => 12,
                'donor_code' => 'DNR012',
                'donor_id' => 'DONOR012',
                'ktp_number' => '1234567890123457',
                'name' => 'Jack Purple',
                'gender' => 'Laki-laki',
                'blood_type' => 'O',
                'rhesus' => 'NEGATIF',
                'birth_date' => '1986-03-03',
                'birth_place' => 'Bali',
                'telephone' => '092345678901',
                'address' => 'Jl. Sample No. 12',
                'province_id' => 12,
                'city_id' => 12,
                'district_id' => 12,
                'village_id' => 12,
                'postal_code' => '67890',
                'rt_rw' => '22/23',
                'occupation' => 'Financial Consultant',
            ],
            [
                'user_id' => 13,
                'donor_code' => 'DNR013',
                'donor_id' => 'DONOR013',
                'ktp_number' => '2345678901234568',
                'name' => 'Liam Blue',
                'gender' => 'Laki-laki',
                'blood_type' => 'A',
                'rhesus' => 'POSITIF',
                'birth_date' => '1990-05-15',
                'birth_place' => 'Surabaya',
                'telephone' => '093456789012',
                'address' => 'Jl. Sample No. 13',
                'province_id' => 13,
                'city_id' => 13,
                'district_id' => 13,
                'village_id' => 13,
                'postal_code' => '13579',
                'rt_rw' => '24/25',
                'occupation' => 'IT Support',
            ],
            [
                'user_id' => 14,
                'donor_code' => 'DNR014',
                'donor_id' => 'DONOR014',
                'ktp_number' => '3456789012345679',
                'name' => 'Mia Green',
                'gender' => 'Perempuan',
                'blood_type' => 'B',
                'rhesus' => 'NEGATIF',
                'birth_date' => '1998-07-20',
                'birth_place' => 'Yogyakarta',
                'telephone' => '094567890123',
                'address' => 'Jl. Sample No. 14',
                'province_id' => 14,
                'city_id' => 14,
                'district_id' => 14,
                'village_id' => 14,
                'postal_code' => '24680',
                'rt_rw' => '26/27',
                'occupation' => 'UX Designer',
            ],
            [
                'user_id' => 15,
                'donor_code' => 'DNR015',
                'donor_id' => 'DONOR015',
                'ktp_number' => '4567890123456780',
                'name' => 'Noah Black',
                'gender' => 'Laki-laki',
                'blood_type' => 'AB',
                'rhesus' => 'POSITIF',
                'birth_date' => '1984-11-11',
                'birth_place' => 'Medan',
                'telephone' => '095678901234',
                'address' => 'Jl. Sample No. 15',
                'province_id' => 15,
                'city_id' => 15,
                'district_id' => 15,
                'village_id' => 15,
                'postal_code' => '13579',
                'rt_rw' => '28/29',
                'occupation' => 'Project Manager',
            ],
        ];

        // Insert data into the profiles table
        DB::table('profiles')->insert($profiles);
    }
}
